# Generated by Django 5.1.5 on 2025-04-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('machine_no', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('RED', 'Red Flag'), ('GREEN', 'Green Flag')], max_length=10)),
                ('issue_type', models.CharField(blank=True, choices=[('MACHINE', 'Machine Issue'), ('FABRIC', 'Fabric Issue'), ('ENVIRONMENTAL', 'Environmental Issue'), ('SYSTEM', 'System Issue'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('machine_no', models.CharField(max_length=10)),
                ('date_of_inspection', models.DateField()),
                ('time_of_inspection', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric_defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='inspection.fabricdefect')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_flags', to='inspection.cliinspector')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_flags', to='inspection.supervisor')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='inspection.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('FLAG', 'Operator Flag'), ('INSPECTION', 'Inspection Update'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inspection.supervisor')),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.flag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
